name: Backend Deployment

on:
  push:
    branches:
      - main  # Adjust as per your main branch name

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install backend dependencies
        run: |
          cd backend  # Replace with your actual backend directory
          npm install

      - name: Build backend (if applicable)
        run: |
          cd backend  # Replace with your actual backend directory
          # Example build command, adjust as per your backend setup
          npm run build

      - name: Restart backend service
        run: |
          cd backend  # Replace with your actual backend directory
          pm2 restart app.js  # Replace 'app.js' with your actual entry file

      # Additional steps as needed for database migrations, etc.
