name: Frontend Deployment

on:
  push:
    branches:
      - main  # Adjust as per your main branch name

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install frontend dependencies
        run: |
          cd frontend  # Replace with your actual frontend directory
          npm install

      - name: Build React App
        run: |
          cd frontend  # Replace with your actual frontend directory
          npm run build

      - name: Deploy frontend to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync frontend/build s3://21mh1a --delete
          # Replace your-frontend-bucket-name with your actual frontend bucket name
