name: Deploy to EC2 Instance

on:
  push:
    branches:
      - main  # Replace with your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install SSH Client
        run: sudo apt-get install -y openssh-client

      - name: Add SSH Private Key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy Backend
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@13.239.15.215 'cd /Users/sriva/OneDrive/Pictures/Desktop/js_projs/final/backend && git pull origin main && npm install && pm2 restart app'

      - name: Deploy Frontend
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@13.239.15.215 'cd /Users/sriva/OneDrive/Pictures/Desktop/js_projs/final/frontend && git pull origin main && npm install && npm run build'
